[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"
  flush_jitter = "2s"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "homelab"
  bucket = "factory-data"
  timeout = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://[YOUR_SERVER_IP]:1883"]
  topics = ["/neuron/mqtt-json"]
  client_id = "telegraf-it-historian"
  qos = 1
  persistent_session = false
  data_format = "json_v2"
  name_override = "plc_tags"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "plc_tags"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "node"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "group"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "values.OperatingMode"
      type = "int"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "values.Fan_On"
      type = "bool"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "values.Green_LED_On"
      type = "bool"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "values.Red_LED_On"
      type = "bool"